function(sdl_private_sources )
  if(TARGET SDL3-shared)
    target_sources(SDL3-shared PRIVATE ${ARGN})
  endif()
  if(TARGET SDL3-static)
    target_sources(SDL3-static PRIVATE ${ARGN})
  endif()
endfunction()

function(sdl_glob_private_sources )
  file(GLOB files ${ARGN})
  sdl_private_sources(PRIVATE ${files})
endfunction()

function(sdl_compile_options )
  if(TARGET SDL3-shared)
    target_compile_options(SDL3-shared ${ARGN})
  endif()
  if(TARGET SDL3-static)
    target_compile_options(SDL3-static ${ARGN})
  endif()
endfunction()

function(sdl_compile_definitions )
  if(TARGET SDL3-shared)
    target_compile_definitions(SDL3-shared ${ARGN})
  endif()
  if(TARGET SDL3-static)
    target_compile_definitions(SDL3-static ${ARGN})
  endif()
endfunction()

function(sdl_include_directories )
  if(TARGET SDL3-shared)
    target_include_directories(SDL3-shared ${ARGN})
  endif()
  if(TARGET SDL3-static)
    target_include_directories(SDL3-static ${ARGN})
  endif()
endfunction()

function(sdl_link_directories )
  if(TARGET SDL3-shared)
    target_link_directories(SDL3-shared ${ARGN})
  endif()
  if(TARGET SDL3-static)
    target_link_directories(SDL3-static ${ARGN})
  endif()
endfunction()

function(sdl_private_link_options )
  if(TARGET SDL3-shared)
    target_link_options(SDL3-shared PRIVATE ${ARGN})
  endif()
  if(TARGET SDL3-static)
    target_link_options(SDL3-static INTERFACE ${ARGN})
  endif()
endfunction()

function(sdl_link_libraries )
  if(TARGET SDL3-shared)
    target_link_libraries(SDL3-shared ${ARGN})
  endif()
  if(TARGET SDL3-static)
    target_link_libraries(SDL3-static ${ARGN})
  endif()
endfunction()
